name: docker-build
version: 0.0.1
inputs:
- name: FLOWCI_DOCKER_BUILD_PATH
  type: string
  required: true
- name: FLOWCI_DOCKER_REGIRTY
  type: string
  required: true
- name: FLOWCI_DOCKER_NAME
  type: string
  required: true

script: |
  echo '#################### Docker Build ####################'
  
  cd ${FLOWCI_DOCKER_BUILD_PATH}

  BRANCH_PREFIX=$(echo $FLOWCI_GIT_BRANCH | awk -F/ '{print $1}')
  
  if [[ ${BRANCH_PREFIX} = 'master' ]]; then
    DOCKER_TAG=master.${FLOWCI_JOB_BUILD_NUM}
  fi

  if [[ ${BRANCH_PREFIX} = 'develop' ]]; then
    DOCKER_TAG=develop.${FLOWCI_JOB_BUILD_NUM}
  fi
  
  if [[ ${BRANCH_PREFIX} = 'feature' ]]; then
    FEATURE_ID=$(echo $FLOWCI_GIT_BRANCH | awk -F/ '{print $2}')
    DOCKER_TAG=feature.${FEATURE_ID}.${FLOWCI_JOB_BUILD_NUM}
  fi

  IMAGE_BUILD=${FLOWCI_DOCKER_REGIRTY}/${FLOWCI_DOCKER_NAME}:${DOCKER_TAG}
  IMAGE_LATEST=${FLOWCI_DOCKER_REGIRTY}/${FLOWCI_DOCKER_NAME}:latest

  echo "Image: ${IMAGE_BUILD}"
  echo "Image: ${IMAGE_LATEST}"

  docker build -t ${IMAGE_BUILD} .
  docker build -t ${IMAGE_LATEST} .

  docker push ${IMAGE_BUILD}
  docker push ${IMAGE_LATEST}
  
  export PLUGIN_OUT_DOCKER_IMAGE=${IMAGE_BUILD}
  
  echo '#################### FINISH ####################'
